#!/bin/bash
#
# Search for music files from current directory and play in random
# order using mplayer.

LIST="m4a\|mp3\|mp4\|wav\|ogg\|wmv\|flv\|flac"

if [ "$1" = "-l" ]; then
	find "$(pwd)" -type f -iregex ".*\.\($LIST\)" | sort -R
else
	mplayer $@ -shuffle -playlist <(find "$(pwd)" -type f -iregex ".*\.\($LIST\)")
fi
